#!/bin/bash

go test -i bitmessage-go/base58
go test -i bitmessage-go/bitecdsa
go test -i bitmessage-go/bitelliptic
go test -i bitmessage-go/ripemd160
go test -i bitmessage-go/varint
go test -i bitmessage-go/address
go test -i bitmessage-go/wif
go test -i bitmessage-go/pow

go test bitmessage-go/varint
go test bitmessage-go/base58
go test bitmessage-go/ripemd160
go test bitmessage-go/address
go test bitmessage-go/wif
go test bitmessage-go/bitelliptic
go test bitmessage-go/bitecdsa
go test bitmessage-go/pow
